import {
  Atom,
  TypeOutline,
  Wind,
  BarChart2,
  Database,
  Server,
  Key,
  Package,
  Smartphone,
  Box,
  Cloud,
  MapPin,
  Github,
  Check,
  ExternalLink,
  Camera,
  Code,
  Boxes,
  BrainCircuit,
  CreditCard,
  BookOpen,
  Clock,
  Globe,
  Star,
  User,
  Users,
  Lock,
  CheckCircle,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  Palette,
  Codepen,
  GitBranch,
  Layout,
  Zap,
  Shuffle,
  Move,
  Activity,
  Shield,
  Layers,
  Wifi,
  Link,
  Share2,
  Mail,
  Image,
  Terminal,
  Flame,
  Library,
  Table,
  BarChart,
  MousePointer,
  Calculator,
  HardDrive,
  Grid,
  Circle,
  PenTool,
  LayoutTemplate,
  MonitorSmartphone,
  Triangle,
  Edit3,
  Leaf,
  MoveLeft,
  ChevronRight,
  ChevronLeft,
  Truck,
  DollarSign,
  Monitor,
  Home,
  Youtube,
  Linkedin,
  Facebook,
  MoveRight,
  X,
} from "lucide-react";

const TechIcon = ({ name, className = "" }) => {
  const icons = {
    atom: <Atom className={className} />,
    typeoutline: <TypeOutline className={className} />,
    wind: <Wind className={className} />,
    "bar-chart-2": <BarChart2 className={className} />,
    database: <Database className={className} />,
    server: <Server className={className} />,
    key: <Key className={className} />,
    package: <Package className={className} />,
    smartphone: <Smartphone className={className} />,
    box: <Box className={className} />,
    cloud: <Cloud className={className} />,
    "map-pin": <MapPin className={className} />,
    github: <Github className={className} />,
    "external-link": <ExternalLink className={className} />,
    check: <Check className={className} />,
    camera: <Camera className={className} />,
    code: <Code className={className} />,
    boxes: <Boxes className={className} />,
    "brain-circuit": <BrainCircuit className={className} />,
    "credit-card": <CreditCard className={className} />,
    "book-open": <BookOpen className={className} />,
    clock: <Clock className={className} />,
    globe: <Globe className={className} />,
    star: <Star className={className} />,
    user: <User className={className} />,
    users: <Users className={className} />,
    lock: <Lock className={className} />,
    "check-circle": <CheckCircle className={className} />,
    "chevron-up": <ChevronUp className={className} />,
    "chevron-down": <ChevronDown className={className} />,
    "arrow-right": <ArrowRight className={className} />,
    palette: <Palette className={className} />,
    codepen: <Codepen className={className} />,
    "git-branch": <GitBranch className={className} />,
    layout: <Layout className={className} />,
    zap: <Zap className={className} />,
    shuffle: <Shuffle className={className} />,
    move: <Move className={className} />,
    activity: <Activity className={className} />,
    shield: <Shield className={className} />,
    layers: <Layers className={className} />,
    wifi: <Wifi className={className} />,
    link: <Link className={className} />,
    "share-2": <Share2 className={className} />,
    mail: <Mail className={className} />,
    image: <Image className={className} />,
    terminal: <Terminal className={className} />,
    library: <Library className={className} />,
    flame: <Flame className={className} />,
    table: <Table className={className} />,
    "bar-chart": <BarChart className={className} />,
    "mouse-pointer": <MousePointer className={className} />,
    calculator: <Calculator className={className} />,
    "hard-drive": <HardDrive className={className} />,
    grid: <Grid className={className} />,
    circle: <Circle className={className} />,
    "pen-tool": <PenTool className={className} />,
    "layout-template": <LayoutTemplate className={className} />,
    "monitor-smartphone": <MonitorSmartphone className={className} />,
    triangle: <Triangle className={className} />,
    "edit-3": <Edit3 className={className} />,
    leaf: <Leaf className={className} />,
    "move-left": <MoveLeft className={className} />,
    "chevron-right": <ChevronRight className={className} />,
    "chevron-left": <ChevronLeft className={className} />,
    truck: <Truck className={className} />,
    "dollar-sign": <DollarSign className={className} />,
    monitor: <Monitor className={className} />,
    home: <Home className={className} />,
    youtube: <Youtube className={className} />,
    linkedin: <Linkedin className={className} />,
    facebook: <Facebook className={className} />,
    "move-right": <MoveRight className={className} />,
    x: <X className={className} />,
  };

  return icons[name.toLowerCase()] || <span className={className}>{name}</span>;
};

export default TechIcon;
