import React , {useState, useEffect} from 'react';
import {motion} from 'framer-motion';
const ThirdSection = ()=>{
     const [showImage, setShowImage] = useState(false);
    
      useEffect(() => {
        const timer = setTimeout(() => {
          setShowImage(true);
        }, 1000); // 2000ms = 2 seconds delay before showing image
    
        return () => clearTimeout(timer);
      }, []);
    return (
        <section className='max-w-6xl mx-auto px-6 py-12'>
            <div className='flex flex-col-reverse md:flex-row items-stretch gap-8'>
                {/* left side */}
                 <div className='flex-1'>
                    <img 
                    src="/images/power-only-dispatch-service.jpg" 
                    alt="Powers Only" 
                    className={`w-full h-full object-cover shadow-lg transition-opacity duration-700 ease-in-out
              ${showImage ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
            `}
            style={{ transitionProperty: 'opacity, transform' }}/>
                </div>
               
                {/* right side */}
                <motion.div 
                className='flex-1 flex flex-col justify-center bg-[#002140] p-6 rounded-lg'
                initial={{ opacity: 0, x: 80 }}
          whileInView={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          viewport={{ once: true }}
                >
                    <h2 className='text-2xl sm:text-3xl md:text-4xl font-bold text-white mt-12 leading-tight'>How does Power Only <span className='text-orange-500'>Dispatching Work</span></h2>
                    <p className='mt-6 text-[11px] sm:text-[13px] md:text-[15px]  text-gray-200 leading-relaxed text-lg'>
                        So, we have plenty of power only shippers out there and a lot of opportunities for tractor owners and trucking companies with a fleet of trailers if they are also ready to provide only power units for shippers.
                    </p>
                     <p className='text-[11px] sm:text-[13px] md:text-[15px]  text-gray-200 leading-relaxed text-lg mt-6'>
                        The question is how to get them matched and arrive at power only rates per mile comparable with income generated by dry van trucking.
                    </p>
                </motion.div>
            </div>
        </section>
    )
}
export default ThirdSection;